### ISSUE TITLE
Image size is half !!!

### ISSUE THREAD

**Issue by alirezaahmadi** [chaowang15/RGBDCapture#11]
I ran the code.. it saves images in half resolution !!! 
could you plz tell me how to change it to original size?
Thanks

**Comment by haojie0713** [comment]
Hi, friend, have you solved the problem? I encountered the same one.

**Comment by alirezaahmadi** [comment]
I have tried different things but unfortunately couldn't get it work correctly .. main issue raises from rgb part which doesn't provide higher resolution than 320*240.. I would share if get any better result.. 
I would really appreciate if you share your result in case of solving the issue too.

**Comment by chaowang15** [comment]
Sorry I don't know this repository is still in use. Haven't updated it for many years since I have no depth camera now. If you cannot get the expected rgb resolution, one possibility is that your device cannot support it. You can print all supported mode of your device using code similar like the commented code here: https://github.com/chaowang15/RGBDCapture/blob/c42ef3955dad46d9389c55d561b5ee24893cdf4b/RGBDCapture/OpenNISensor.cpp#L89
